# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  database: notekeeping_dev

test:
  <<: *default

production:
  <<: *default
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev
